// <auto-generated />
using System;
using MVC_trabajo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_trabajo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926230421_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_trabajo.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editorial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2006,
                            Autor = "Rick Riordan",
                            Cantidad = 56,
                            Categoria = "Fantasía",
                            Editorial = "Salamandra",
                            ISBN = "F-01",
                            Titulo = "Percy Jackson y el ladrón del rayo"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2016,
                            Autor = "Lewis Carroll",
                            Cantidad = 24,
                            Categoria = "Fantasía",
                            Editorial = "Anaya",
                            ISBN = "F-02",
                            Titulo = "Alicia en el País de las Maravillas"
                        },
                        new
                        {
                            Id = 3,
                            Anio = 1943,
                            Autor = "Antoine de Saint-Exupéry",
                            Cantidad = 30,
                            Categoria = "Clásico",
                            Editorial = "Salamandra",
                            ISBN = "F-03",
                            Titulo = "El Principito"
                        },
                        new
                        {
                            Id = 4,
                            Anio = 1967,
                            Autor = "Gabriel García Márquez",
                            Cantidad = 15,
                            Categoria = "Literatura",
                            Editorial = "Sudamericana",
                            ISBN = "L-01",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            Id = 5,
                            Anio = 1605,
                            Autor = "Miguel de Cervantes",
                            Cantidad = 10,
                            Categoria = "Clásico",
                            Editorial = "RAE",
                            ISBN = "L-02",
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            Id = 6,
                            Anio = 1997,
                            Autor = "J.K. Rowling",
                            Cantidad = 40,
                            Categoria = "Fantasía",
                            Editorial = "Salamandra",
                            ISBN = "F-04",
                            Titulo = "Harry Potter y la piedra filosofal"
                        },
                        new
                        {
                            Id = 7,
                            Anio = 2003,
                            Autor = "Dan Brown",
                            Cantidad = 20,
                            Categoria = "Thriller",
                            Editorial = "Umbriel",
                            ISBN = "T-01",
                            Titulo = "El código Da Vinci"
                        },
                        new
                        {
                            Id = 8,
                            Anio = 2010,
                            Autor = "John Zelle",
                            Cantidad = 18,
                            Categoria = "Tecnología",
                            Editorial = "McGraw-Hill",
                            ISBN = "T-02",
                            Titulo = "Introducción a la Programación"
                        },
                        new
                        {
                            Id = 9,
                            Anio = 2008,
                            Autor = "Robert C. Martin",
                            Cantidad = 12,
                            Categoria = "Tecnología",
                            Editorial = "Prentice Hall",
                            ISBN = "T-03",
                            Titulo = "Clean Code"
                        },
                        new
                        {
                            Id = 10,
                            Anio = 1954,
                            Autor = "J.R.R. Tolkien",
                            Cantidad = 35,
                            Categoria = "Fantasía",
                            Editorial = "Minotauro",
                            ISBN = "F-05",
                            Titulo = "El Señor de los Anillos"
                        });
                });

            modelBuilder.Entity("MVC_trabajo.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("MVC_trabajo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasena = "123456",
                            Correo = "admin@gmail.com",
                            Nombre = "Administrador",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Contrasena = "123456",
                            Correo = "biblio@gmail.com",
                            Nombre = "Bibliotecario",
                            Rol = "Bibliotecario"
                        },
                        new
                        {
                            Id = 3,
                            Contrasena = "123456",
                            Correo = "usuario@gmail.com",
                            Nombre = "Usuario Normal",
                            Rol = "Usuario"
                        });
                });

            modelBuilder.Entity("MVC_trabajo.Models.Prestamo", b =>
                {
                    b.HasOne("MVC_trabajo.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_trabajo.Models.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MVC_trabajo.Models.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("MVC_trabajo.Models.Usuario", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
